forced punctuation update
gkorepanov/whisper-stream pull request #3
Opened 2023-07-20 10:51 UTC by tartarus8

2023-07-20 11:02 UTC, gkorepanov requested changes

2023-07-20 11:02 UTC, gkorepanov commented on whisperstream/languages.py
> +
Have you checked that all languages are present?
Also please add space after colons

2023-07-20 11:02 UTC, gkorepanov commented on whisperstream/languages.py
> +def get_punctuation_prompt_for_lang(lang: Lang):
Add type hint for return type

2023-07-20 11:02 UTC, gkorepanov commented on whisperstream/stream.py
> +def is_punctuation_present(text):
add type hints

2023-07-20 11:02 UTC, gkorepanov commented on whisperstream/stream.py
> +        if i.isupper():
Let's return True only if text contains at least one uppercase letter and at least one punctuation sign.

Something like

```python
if not any(x.isupper() for x in text):
    return False
if not any(x in PUNCTUATION_MARKS for x in text):
   return False
```

2023-07-20 11:02 UTC, gkorepanov commented on whisperstream/stream.py
> +        force_punctuation: Locates rare cases of missed punctuation and forces it if necessary
Please add type to comment and split in two lines

2023-07-20 11:02 UTC, gkorepanov commented on whisperstream/stream.py
> +        force_punctuation: Locates rare cases of missed punctuation and forces it if necessary
Same

2023-07-20 11:02 UTC, gkorepanov commented on whisperstream/stream.py
> +        if kwargs.get("prompt") is not None:  # checking if user added initial prompt
this comment does not add any sense. Instead add comment which explains that it is unclear what to do in case user provided custom prompt

2023-07-20 11:02 UTC, gkorepanov commented on whisperstream/stream.py
> +        r = await __transcribe(start=start, end=end)
why no kwargs here?

2023-07-20 11:08 UTC, tartarus8 commented on whisperstream/languages.py
> +
This list of languages corresponds WHISPER_LANGUAGES one

2023-07-21 09:46 UTC, gkorepanov requested changes

2023-07-21 09:46 UTC, gkorepanov commented on whisperstream/stream.py
> +        force_punctuation: (bool): Locates rare cases of missed punctuation
bool, optional

2023-07-21 09:46 UTC, gkorepanov commented on whisperstream/stream.py
> +        force_punctuation: (bool): Locates rare cases of missed punctuation
same

2023-07-21 09:46 UTC, gkorepanov commented on whisperstream/stream.py
> +
why extra line here?

2023-07-21 09:46 UTC, gkorepanov commented on whisperstream/stream.py
> +
why extra line here?

2023-07-21 09:46 UTC, gkorepanov commented on whisperstream/stream.py
> +            raise ValueError("cannot set both prompt and force_punctuation")
Weird indentation

2023-07-21 09:46 UTC, gkorepanov commented on whisperstream/stream.py
> +            raise ValueError("cannot set both prompt and force_punctuation")
Also let's be more specific on error:
```python
raise ValueError(
    "Cannot enforce punctuation when custom prompt is used. "
    "Please set `force_punctuation` to False"
)
```

2023-07-21 09:46 UTC, gkorepanov commented on whisperstream/stream.py
> +
Weird spaces

2023-07-21 09:46 UTC, gkorepanov commented on whisperstream/stream.py
> +        kwargs["prompt"] = get_punctuation_prompt_for_lang(language.pt1)
Let's pass language, not pt1 here. It will be more robust

2023-07-21 09:46 UTC, gkorepanov commented on whisperstream/stream.py
> +    r = await __transcribe(start=start, end=end)
Why no kwargs here?

2023-07-21 10:55 UTC, gkorepanov requested changes

2023-07-21 10:55 UTC, gkorepanov commented on whisperstream/stream.py
> +def is_punctuation_present(text: str):
add return type hint

2023-07-24 11:11 UTC, merged